### ISSUE TITLE
Provide more than just context as a second parameter to batchLoadFn

### ISSUE THREAD

**Issue by quidcain** [slaypni/type-graphql-dataloader#19]
I use field arguments to build a complex query inside of the `@Loader` `batchLoadFn`. With the current code I have to put this arguments as an object parameter of `dataLoader.load` like this:
```
photos(@Root() root: User, @Arg("size", { nullable: true }) size?: string) {
  return (dataloader: DataLoader<number, Photo[]>) =>
    dataloader.load({
      id: root.id,
      size: size,
    });
}
```

But arguments could have been extracted directly from the `batchLoadFn`, if `Loader.ts` had provided all the `resolverData` instead of just `{ context }`

**Comment by slaypni** [comment]
The reason of passing only `context` instead of `ResolverData` into `batchLoadFn` is I thought developers could encounter unintentional bugs unless understanding how it works.
In your case, if there are multiple photos in GraphQL query, the same `root`, `args` could be read from `photo`s' `batchLoadFn`.
`context` will be safe since it refers the same instance, however others in `resolverData` would be problematic.
Therefore, though it seems tedious, getting args from fieldResolver and passing it into `load()` is how it is designed to be.

**Comment by quidcain** [comment]
Thanks for the brilliant explanation @slaypni!
I lost sight of the case with several aliased fields which result in different arguments.
Now design is clear for me.
