### ISSUE TITLE
Planning on using type-graphql-dataloader with graphql-modules and accountsjs

### ISSUE THREAD

**Issue by agustif** [slaypni/type-graphql-dataloader#4]
Hi @slaypni Great project btw! thanks for helping me with my issues before.

Do you think I should have any problem integrating this into my current project?

I'm gonna try to do so following the README.md instructions!

Will keep this as a doc of my own if that's ok or to ask further questions.

Anything you might wanna add/share might be helpful too!

**Comment by slaypni** [comment]
I don't expect any particular problems as long as it is using the latest apollo-server and type-graphql (and typeorm).
Still, something unexpected might happen since `type-graphql-dataloader` itself is not matured.

I think that it would be nicer to open an issue against each topic (problem) so that open/close would be explicit instead of keeping this issue open.
